/*
 * PsidList.h
 *
 *  Created on: 2020Äê4ÔÂ8ÈÕ
 *      Author: cojims
 */

#ifndef SRC_VEINS_MODULES_EDGECOMPUTING_PSIDLIST_H_
#define SRC_VEINS_MODULES_EDGECOMPUTING_PSIDLIST_H_


enum PSIDS {PSIDTSK=10, BROADCASTINFO,TSKREQUESTPACKET};

/*PSIDTSK=10:WSM for task
 * BROADCASTINFO:information broadcasted by edge servers
 * TSKREQUESTPACKET:task informations
 *
 */


enum chosenRSUway {SIMPLEWAY=0, LYAPUNOVWAY=1,PASSIVEWAY=2,GREDDY=3,LYAPUNOVMATLAB=4};

#endif /* SRC_VEINS_MODULES_EDGECOMPUTING_PSIDLIST_H_ */
